---
name: Bug report
description: Create a report to help us improve
labels: ["bug"]
assignees: [""]
body:
  - type: textarea
    id: concise-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: What is the bug about?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: How do we reproduce it?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Anything that will help us triage the bug.
      placeholder: |
        - Module version
        - Terraform version
        - Grafana Version
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
