---
name: Feature Request
description: Suggest an idea for this project
labels: ["feature request"]
assignees: [""]
body:
  - type: textarea
    id: concise-description
    attributes:
      label: Describe the Feature
      description: A clear and concise description of what the feature is.
      placeholder: What is the feature about?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Is your feature request related to a problem/challenge you are trying
        to solve?

        Please provide some additional context of why this feature or
        capability will be valuable.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
